version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user_akademik
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: oulad_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: